

-- 游戏基本信息表
CREATE TABLE IF NOT EXISTS `game_info`  (
    `id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '主键',
    `name` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '游戏名称',
    `kdt_id` BIGINT NOT NULL COMMENT '店铺ID',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_kdt` (`kdt_id`) COMMENT '店铺索引'
) ENGINE=InnoDB CHARSET=utf8mb4 COMMENT='游戏基本信息表';

-- 积分发放记录
CREATE TABLE IF NOT EXISTS `integral_history` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '主键',
    `kdt_id` BIGINT NOT NULL COMMENT '店铺ID',
    `yz_open_id` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '有赞ID',
--     `telephone` VARCHAR(11) NOT NULL DEFAULT '' COMMENT '手机号',
    `integral_num` INT NOT NULL COMMENT '积分发放数量',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_kdt` (`kdt_id`) COMMENT '店铺索引'
) ENGINE=InnoDB CHARSET=utf8mb4 COMMENT='游戏基本信息表';

-- 订购信息表
CREATE TABLE IF NOT EXISTS `order_info` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '主键',
    `kdt_id` BIGINT NOT NULL COMMENT '店铺ID',
    `effect_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '生效时间',
    `expire_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '过期时间',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_kdt` (`kdt_id`) COMMENT '店铺索引'
) ENGINE=InnoDB CHARSET=utf8mb4 COMMENT='游戏基本信息表';